Add good/bad code examples.
codelingo/rules pull request #16
Opened 2020-09-28 22:18 UTC by meadows115

2020-09-29 00:08 UTC, mrcrowl requested changes
LGTM with some minor tweaks.

2020-09-29 00:08 UTC, mrcrowl commented on rules/codelingo/effective-go/reuse-variable-name-type-switch/codelingo.yaml
> +        title: Reuse Variable Name In A Type Switch
```suggestion
        title: Reuse Variable Name in a Type Switch
```

2020-09-29 00:08 UTC, mrcrowl commented on rules/codelingo/effective-go/reuse-variable-name-type-switch/codelingo.yaml
> +        [as specified in Effective Go](https://golang.org/doc/effective_go.html#type_switch)
```suggestion
        From [Effective Go](https://golang.org/doc/effective_go.html#type_switch).
```

2020-09-29 00:08 UTC, mrcrowl commented on rules/codelingo/effective-go/reuse-variable-name-type-switch/codelingo.yaml
> +              switch i := i.(type) {
```suggestion
              switch i := i.(type) { // <-- reuse of variable i here.
```

2020-09-29 00:08 UTC, mrcrowl commented on rules/codelingo/effective-go/reuse-variable-name-type-switch/codelingo.yaml
> +              switch i := i.(type) {
I've added a comment here, just because this one is relatively hard to visually spot-the-difference. Loving the realistic code samples, though! 👍

2020-10-04 21:02 UTC, Daanikus approved these changes

2020-10-04 21:07 UTC, mrcrowl approved these changes
LGTM

2020-10-04 21:08 UTC, merged